package com.bae.tests.frontend;

import static org.junit.Assert.assertEquals;

import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class FrontendUseCaseTest {

	private static WebDriver driver;
	private static final String ROOT_LOCATION = "http://34.77.62.121:8888/BAESoloProject/";
	private static final String INDEX_LOCATION = ROOT_LOCATION + "index.html";

	@BeforeClass
	public static void setup() {
		System.setProperty("webdriver.chrome.driver", "c:/chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("headless");
		options.addArguments("window-size=1200x600");
		driver = new ChromeDriver(options);
	}

	@AfterClass
	public static void teardown() {
		driver.quit();
	}

	@Before
	public void init() {
		driver.get(INDEX_LOCATION);
	}

	@Test
	public void useCase1() {// View all champions
		driver.findElement(By.xpath("//*[@id=\"navbarNavAltMarkup\"]/div/a[2]")).click();
		assertEquals(ROOT_LOCATION + "champions.html", driver.getCurrentUrl());
		body();
	}

	@Test
	public void useCase2() {// View all playable character classes (roles)
		driver.findElement(By.xpath("//*[@id=\"navbarNavAltMarkup\"]/div/a[4]")).click();
		assertEquals(ROOT_LOCATION + "roles.html", driver.getCurrentUrl());
		body();

	}

	@Test
	public void useCase3() {// View included pantheons
		driver.findElement(By.xpath("//*[@id=\"navbarNavAltMarkup\"]/div/a[5]")).click();
		assertEquals(ROOT_LOCATION + "pantheons.html", driver.getCurrentUrl());
		body();

	}

	@Test
	public void useCase4() {// View game modes
		driver.findElement(By.xpath("//*[@id=\"navbarNavAltMarkup\"]/div/a[6]")).click();
		assertEquals(ROOT_LOCATION + "gamemodes.html", driver.getCurrentUrl());
		body();

	}

	@Test
	public void useCase5() {// View all recorded stats
		driver.findElement(By.xpath("//*[@id=\"navbarNavAltMarkup\"]/div/a[3]")).click();
		assertEquals(ROOT_LOCATION + "stats.html", driver.getCurrentUrl());
		body();
	}

	public void body() {

		// The rendered table body.
		// This isn't present until the js generates and populate the table
		WebElement ele = (new WebDriverWait(driver, 15))
				.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"tbl\"]/tbody")));

		assertEquals(true, ele.isDisplayed());

		// The edit button for the first record generated by the js
		ele = (new WebDriverWait(driver, 15)).until(ExpectedConditions.presenceOfElementLocated(By.id("1")));

		System.out.println(driver.getCurrentUrl());
		assertEquals(true, ele.getText().contains("Edit"));
	}
}
